/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryRouteImport } from './routes/category'
import { Route as DuelRouteImport } from './routes/duel'
import { Route as GameRouteImport } from './routes/game'
import { Route as NextRouteImport } from './routes/next'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as WinnerRouteImport } from './routes/winner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelRoute = DuelRouteImport.update({
  id: '/duel',
  path: '/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const NextRoute = NextRouteImport.update({
  id: '/next',
  path: '/next',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const WinnerRoute = WinnerRouteImport.update({
  id: '/winner',
  path: '/winner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/category': typeof CategoryRoute
  '/duel': typeof DuelRoute
  '/game': typeof GameRoute
  '/next': typeof NextRoute
  '/tournament': typeof TournamentRoute
  '/winner': typeof WinnerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/category': typeof CategoryRoute
  '/duel': typeof DuelRoute
  '/game': typeof GameRoute
  '/next': typeof NextRoute
  '/tournament': typeof TournamentRoute
  '/winner': typeof WinnerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/category': typeof CategoryRoute
  '/duel': typeof DuelRoute
  '/game': typeof GameRoute
  '/next': typeof NextRoute
  '/tournament': typeof TournamentRoute
  '/winner': typeof WinnerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/category' | '/duel' | '/game' | '/next' | '/tournament' | '/winner'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/category' | '/duel' | '/game' | '/next' | '/tournament' | '/winner'
  id:
    | '__root__'
    | '/'
    | '/category'
    | '/duel'
    | '/game'
    | '/next'
    | '/tournament'
    | '/winner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryRoute: typeof CategoryRoute
  DuelRoute: typeof DuelRoute
  GameRoute: typeof GameRoute
  NextRoute: typeof NextRoute
  TournamentRoute: typeof TournamentRoute
  WinnerRoute: typeof WinnerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel': {
      id: '/duel'
      path: '/duel'
      fullPath: '/duel'
      preLoaderRoute: typeof DuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next': {
      id: '/next'
      path: '/next'
      fullPath: '/next'
      preLoaderRoute: typeof NextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winner': {
      id: '/winner'
      path: '/winner'
      fullPath: '/winner'
      preLoaderRoute: typeof WinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryRoute: CategoryRoute,
  DuelRoute: DuelRoute,
  GameRoute: GameRoute,
  NextRoute: NextRoute,
  TournamentRoute: TournamentRoute,
  WinnerRoute: WinnerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
